name: Auto News Update
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests beautifulsoup4 lxml

      - name: Run crawler
        run: python main.py

      - name: Commit & Push
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add news.json
          git commit -m "auto update real news" || echo "无变更无需提交"
          git push
